name: Log PR data

on:
  issues:
    types: [assigned]
  issue_comment:
    types: [created]
  pull_request:
    types: [closed]

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
      - name: Validate if is codeowner
        # if: ${{github.event.pull_request.author_association == OWNER }}
        run: |
          echo ${{github.event.pull_request.author_association}}
          echo ${{github.event.pull_request.issue_url}}
          echo ${{github.event.issue.author_association}}

  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue Branch
        id: create-work-branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Echo branch name
        run: echo ${{ steps.create-work-branch.outputs.branchName }}
